@@ -84,6 +84,7 @@
 obj-$(CONFIG_ST_FDMA) += st_fdma.o
 obj-$(CONFIG_FSL_DPAA2_QDMA) += fsl-dpaa2-qdma/
 obj-$(CONFIG_INTEL_LDMA) += lgm/
+obj-$(CONFIG_ARM_DMA350) += arm_dma350.o
 
 obj-y += amd/
 obj-y += mediatek/
