# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/common
ccflags-y += -I$(srctree)/drivers/media/platform/cix/cix_isp/platform/logger
ccflags-y += -DARMCB_CAM_AHB

obj-y += cix_vi_hw.o
